### ISSUE TITLE
Support multiple distinct UIs

### ISSUE THREAD

**Issue by fozziethebeat** [fastify/fastify-swagger-ui#55]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

With ChatGPT plugins depending on OpenAPI specifications, it would be really helpful if there's a simplified way to create at least two distinct OpenAPI specifications and Swagger UI's.  Each version would have to live under distinct URL routes.  They would both consume the same underlying `swaggerObject` but would likely have different `transformSpecification` functions to selectively reveal or hide different routes.

Ideally this is done by registering the swagger ui plugin multiple times and configuring them appropriately.

Right now this doesn't work because the plugin does some decorations that clash on the second registration.

### Motivation

This would make it trivial to run and manage a single server that has an API service that's suitable for OpenAI plugins with a subset of routes supported and a wider set of API routes that are available for other clients, such as a web app.

### Example

An example setup could be:

```javascript
  await fastify.register(require("@fastify/swagger-ui"), {
    routePrefix: "/internal-documentation",
    uiConfig: {
      docExpansion: "full",
      deepLinking: false,
    },
    uiHooks: {
      onRequest: function (request, reply, next) {
        next();
      },
      preHandler: function (request, reply, next) {
        next();
      },
    },
    staticCSP: true,
    transformStaticCSP: (header) => header,
    transformSpecification: internalAPITransformation,
    transformSpecificationClone: true,
  });
  await fastify.register(require("@fastify/swagger-ui"), {
    routePrefix: "/external-documentation",
    uiConfig: {
      docExpansion: "full",
      deepLinking: false,
    },
    uiHooks: {
      onRequest: function (request, reply, next) {
        next();
      },
      preHandler: function (request, reply, next) {
        next();
      },
    },
    staticCSP: true,
    transformStaticCSP: (header) => header,
    transformSpecification: externalAPITransformation,
    transformSpecificationClone: true,
  });
```

**Comment by mcollina** [comment]
What error are you getting when running the above? This should be feasible to achieve.

**Comment by fozziethebeat** [comment]
I'm getting the following error from Fastify:

```
[App] FastifyError [Error]: The decorator 'swaggerCSP' has already been added!
[App]     at decorate (/Users/fozziethebeat/devel/durable/AI-API/node_modules/fastify/li
b/decorate.js:23:11)
[App]     at Object.decorateFastify [as decorate] (/Users/fozziethebeat/devel/durable/AI-API/node_modules/fastify/lib/decorate.js:67:3)
[App]     at fastifySwaggerUi (/Users/fozziethebeat/devel/durable/AI-API/node_modules/@fastify/swagger-ui/index.js:7:11)
[App]     at Plugin.exec (/Users/fozziethebeat/devel/durable/AI-API/node_modules/avvio/p
lugin.js:130:19)
[App]     at Boot.loadPlugin (/Users/fozziethebeat/devel/durable/AI-API/node_modules/avvio/plugin.js:272:10)
[App]     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
 {
[App]   code: 'FST_ERR_DEC_ALREADY_PRESENT',
[App]   statusCode: 500
[App] }
```

I'm guessing it's as simple as making that csp object more uniquely named each time the plugin is registered.

**Comment by Eomm** [comment]
You need to create two encapsulated contexts.
Here is an example with another plugin - but the code would be the same:
https://stackoverflow.com/questions/75938106/is-there-any-way-to-configure-fastify-caching-per-route/

**Comment by fozziethebeat** [comment]
Well, something new i just learned about Fastify.  That absolutely solved the problem with just a few line changes.  Thank you!

**Comment by ThomasKoscheck** [comment]
@fozziethebeat I have the same problem, can you share how you exactly did it?

**Comment by fozziethebeat** [comment]
I sadly have forgotten what I did here

**Comment by Infiee** [comment]
> [@fozziethebeat](https://github.com/fozziethebeat) I have the same problem, can you share how you exactly did it?我遇到了同样的问题，你能分享一下你具体是怎么解决的吗？

My solution code requires creating a separate scope for the plugin, referring to the registration method of Swagger UI in the code.

```ts
import fp from "fastify-plugin";
import swagger from "@fastify/swagger";
import swaggerUi from "@fastify/swagger-ui";
import { FastifyRequest, FastifyReply } from "fastify";

export interface SwaggerPluginOptions {}

/**
 * This plugins adds swagger ui to the fastify instance
 *
 * @see https://github.com/fastify/fastify-swagger
 * @see https://github.com/fastify/fastify-swagger-ui
 */
export default fp<SwaggerPluginOptions>(
  async (fastify) => {
    // 注册Client API Swagger配置
    await fastify.register(swagger, {
      openapi: {
        info: {
          title: "Client API",
          description: "Client API with Swagger",
          version: "1.0.0",
        },
        components: {
          securitySchemes: {
            bearerAuth: {
              type: "http",
              scheme: "bearer",
              bearerFormat: "JWT"
            }
          }
        },
        security: [{
          bearerAuth: []
        }]
      },
      // 排除 /api/admin 开头的路由
      transform: ({ schema, url, route }) => {
        if (url.startsWith("/api/admin")) {
          return { schema: { ...schema, hide: true }, url };
        }
        return { schema, url };
      },
      decorator: 'clientSwagger'
    });

    // 注册Admin API Swagger配置
    await fastify.register(swagger, {
      openapi: {
        info: {
          title: "Admin API",
          description: "Admin API with Swagger",
          version: "1.0.0",
        },
        components: {
          securitySchemes: {
            bearerAuth: {
              type: "http",
              scheme: "bearer",
              bearerFormat: "JWT"
            }
          }
        },
        security: [{
          bearerAuth: []
        }]
      },
      // 只包含 /api/admin 开头的路由
      transform: ({ schema, url, route }) => {
        if (!url.startsWith("/api/admin")) {
          return { schema: { ...schema, hide: true }, url };
        }
        return { schema, url };
      },
      decorator: 'adminSwagger'
    });
    
    // 注册Client Swagger UI，使用独立的插件注册作用域
    fastify.register(async (instance) => {
      await instance.register(swaggerUi, {
        routePrefix: "/docs/client",
        uiConfig: {
          docExpansion: "list",
          deepLinking: true,
          persistAuthorization: true,
        },
        staticCSP: true,
        transformSpecification: (swaggerObject: any, request: FastifyRequest, reply: FastifyReply) => {
          return fastify.clientSwagger();
        },
        transformSpecificationClone: true,
        logLevel: "silent"
      });
    });
    
    // 注册Admin Swagger UI，使用独立的插件注册作用域
    fastify.register(async (instance) => {
      await instance.register(swaggerUi, {
        routePrefix: "/docs/admin",
        uiConfig: {
          docExpansion: "list",
          deepLinking: true,
          persistAuthorization: true,
        },
        staticCSP: true,
        transformSpecification: (swaggerObject: any, request: FastifyRequest, reply: FastifyReply) => {
          return fastify.adminSwagger();
        },
        transformSpecificationClone: true,
        logLevel: "silent"
      });
    });

    fastify.log.info("【swagger Plugin】注册成功.");
  },
  {
    name: "swagger",
    fastify: "^5.x",
  }
);

// When using .decorate you have to specify added properties for Typescript
declare module "fastify" {
  export interface FastifyInstance {
    clientSwagger: FastifyInstance['swagger'];
    adminSwagger: FastifyInstance['swagger'];
  }
}

```
